[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B58F3B2E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/789044ff5f762c99393dab266f479156
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B58F3B0790>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/789044ff5f762c99393dab266f479156
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B58F3B3990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/789044ff5f762c99393dab266f479156